# Generated by Django 3.2.5 on 2021-07-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Realistic', models.FloatField()),
                ('Investigative', models.FloatField()),
                ('Artistic', models.FloatField()),
                ('Social', models.FloatField()),
                ('Enterprising', models.FloatField()),
                ('Conventional', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
