# Generated by Django 3.2.5 on 2021-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_personality',
            name='Artistic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_personality',
            name='Conventional',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_personality',
            name='Enterprising',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_personality',
            name='Investigative',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_personality',
            name='Realistic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_personality',
            name='Social',
            field=models.IntegerField(),
        ),
    ]
